# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wwdc < Formula
  desc "A CLI tool to scrape and export WWDC session videos"
  homepage "https://github.com/antoniopantaleo/wwdc"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/antoniopantaleo/wwdc/releases/download/v0.1.3/wwdc_Darwin_x86_64.tar.gz"
      sha256 "e3a69aef73bf64d5891fe09b99133291163a0d9842dcb45671a3e4073fc52e9e"

      define_method(:install) do
        bin.install "wwdc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/antoniopantaleo/wwdc/releases/download/v0.1.3/wwdc_Darwin_arm64.tar.gz"
      sha256 "8d7e515c0ef33c0fb423bbc15536866f891cdf0e1411b147ecc4b11d071a7022"

      define_method(:install) do
        bin.install "wwdc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/antoniopantaleo/wwdc/releases/download/v0.1.3/wwdc_Linux_x86_64.tar.gz"
      sha256 "064803bdda5bbf17ab038ea0d70247c95b87520d38bba1bc087abf70ba7b193d"
      define_method(:install) do
        bin.install "wwdc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/antoniopantaleo/wwdc/releases/download/v0.1.3/wwdc_Linux_arm64.tar.gz"
      sha256 "2a49dac2d8c6878e99f2b3eefaea5da9763b12229d182c90a823b6dcfaa3db0e"
      define_method(:install) do
        bin.install "wwdc"
      end
    end
  end

  test do
    system "#{bin}/wwdc", "--version"
  end
end
